version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mjgh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mjgh
      JWT_SECRET: supersecret
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data:
